name: Weather Scrapper Tests

on:
  push:
    branches:
      - HLA-26
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Fix permissions
      run: |
        cd backend
        chmod +x ./node_modules/.bin/jest

    - name: Run tests
      run: |
        cd backend
        npm test

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: backend/test-results
